baseURL = "https://blog.freakydu.de/" # The URL of your site.
theme = "zzo" # Name of Zzo theme folder in `themes/`.
title = "Freakydude's page" # Title of your site

defaultContentLanguage = "en" # Default language to use (if you setup multilingual)
defaultContentLanguageInSubdir = true # baseURL/en/, baseURL/kr/ ...
hasCJKLanguage = false # Set `true` for Chinese/Japanese/Korean languages.

buildFuture = true # if true, we can use future date for talks page
summaryLength = 70 # The length of a post description on a list page.

copyright = "©{year}, All Rights Reserved" # copyright symbol: $copy; current year: {year}
enableEmoji = true 
enableRobotsTXT = false 
paginate = 13 # Number of items per page in paginated lists.
rssLimit = 100 
timeout = 10000 

enableGitInfo = false # When true, the modified date will appear on a summary and single page. Since GitHub info needs to be fetched, this feature will slow down to build depending on a page number you have
googleAnalytics = "" 

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = true
unsafe = true
xHTML = true
[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
section = ["HTML", "RSS", "SearchIndex"]
taxonomy = ["HTML", "RSS", "SearchIndex"]
taxonomyTerm = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
[outputFormats.SearchIndex]

baseName = "index"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
