[en]
contentdir = "content/en"
languageName = "English"
languagedir = "ltr"
title = "FreakyDude's page"
weight = 1

[de]
contentdir = "content/de"
languageName = "Deutsch"
languagedir = "ltr"
title = "FreakyDude's Seite"
weight = 2
