baseURL: "https://blog.freakydu.de/"
title: freakyDude's Blog
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: freakyDude's Blog
  description: "My blog to remember and share knowledge I'm working on. As always in search of smart solutions."
  keywords: [Blog, DJ, Tech, 3D Printer, Development]
  author: "freakyDude"
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/apple-touch-icon.png"

  label:
    text: "freakyDude"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: freakyDude
    subtitle: "in search of smart solutions"
    imageUrl: "/apple-touch-icon.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: freakyDude logo
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Search
        url: search

  # home-info mode
  homeInfoParams:
    Title: "freakyDude's blog"
    Content: in search of smart solutions
  socialIcons:
    - name: github
      url: "https://github.com/freakydude/"
    #    - name: paypal
    #      url: "https://www.paypal.com/paypalme/frashman"
    #    - name: buymeacoffee
    #      url: "https://www.buymeacoffee.com/freakydude"
    - name: kofi
      url: "https://ko-fi.com/freakydude"
    - name: youtube
      url: "https://www.youtube.com/channel/UCnbeRiftkkyCWVawZTrCXYQ/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/freakydude/freakydude.github.io/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: archives
      url: /archives/
      weight: 40
    - identifier: about
      name: about
      url: /about/
      weight: 50

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: false

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
