version: "3.8"
services:
  build:
    image: klakegg/hugo:ext-alpine
    volumes:
        - ".:/src"
  server:
    image: klakegg/hugo:ext-alpine
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"